/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumCardMini: typeof import('./src/components/AlbumCardMini.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    BandCardMini: typeof import('./src/components/BandCardMini.vue')['default']
    BandMember: typeof import('./src/components/BandMember.vue')['default']
    CollapsibleText: typeof import('./src/components/CollapsibleText.vue')['default']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    CustomButton: typeof import('./src/components/inputs/CustomButton.vue')['default']
    CustomDropdown: typeof import('./src/components/inputs/CustomDropdown.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    CustomTextarea: typeof import('./src/components/inputs/CustomTextarea.vue')['default']
    DatabaseSearch: typeof import('./src/components/DatabaseSearch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileTreeItem: typeof import('./src/components/FileTreeItem.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MemberBands: typeof import('./src/components/MemberBands.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MusicFileTree: typeof import('./src/components/MusicFileTree.vue')['default']
    NginxFileBrowser: typeof import('./src/components/NginxFileBrowser.vue')['default']
    NumberInput: typeof import('./src/components/inputs/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SelectInput: typeof import('./src/components/inputs/SelectInput.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    TextInput: typeof import('./src/components/inputs/TextInput.vue')['default']
  }
}
